---
abstract: 'utility functions to create Pandoc documents'
author:
  - 'Jakob Voß <jakob.voss@gbv.de>'
build_requires:
  Test::More: 0.96
configure_requires:
  Module::Build::Tiny: 0.038
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pandoc-Elements
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/nichtich/Pandoc-Elements/issues
  homepage: https://github.com/nichtich/Pandoc-Elements
  repository: https://github.com/nichtich/Pandoc-Elements.git
version: 0.01
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
